##
## Makefile for libs in /home/aslafy_z/Lib/
##
## Made by Zadkiel Aslafy Aharonian
## Login   <aslafy_z@epitech.net>
##
## Started on  Mon Oct 21 11:21:36 2013 Zadkiel Aslafy Aharonian
## Last update Wed Jun  4 16:42:39 2014 Zadkiel Aslafy-Aharonian
##

all:
	make -C my/
	make -C myx/
	make -C parson/

clean:
	make -C my/ clean
	make -C myx/ clean
	make -C parson/ clean

re:
	make -C my/ re
	make -C myx/ re
	make -C parson/ re

fclean:
	make -C my/ fclean
	make -C myx/ fclean
	make -C parson/ fclean

.PHONY: all clean re fclean
